"""Named chat histories (.remie/chats/<uuid>.json)."""

import datetime as _dt
import json
import uuid
from pathlib import Path
from typing import Any

from remie.tools.common import _remie_dir, _write_json_atomic
from remie.storage.memories import MEMORY_NAME_MAX_CHARS


def session_file_path() -> Path:
    return _remie_dir() / "session.json"


# --- Chats ------------------------------------------------------------------
#
# Chats are named conversation histories, separate from durable notes.
# .remie/chats/index.json maps uuid -> {name, created_at, updated_at, model};
# each chat's messages live in .remie/chats/<uuid>.json.

CHAT_INDEX_VERSION = 1
CHAT_FILE_VERSION = 1
LEGACY_SESSION_VERSION = 1
DEFAULT_CHAT_NAME = "New chat"


def chat_dir() -> Path:
    return _remie_dir() / "chats"


def chat_index_path() -> Path:
    return chat_dir() / "index.json"


def chat_file_path(chat_id: str) -> Path:
    return chat_dir() / f"{chat_id}.json"


def load_chat_index() -> dict[str, Any]:
    """Return {uuid: {name, created_at, updated_at, model}} (empty if absent)."""
    path = chat_index_path()
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except OSError, UnicodeError, json.JSONDecodeError:
        return {}
    chats = data.get("chats")
    return chats if isinstance(chats, dict) else {}


def save_chat_index(chats: dict[str, Any]) -> None:
    _write_json_atomic(
        chat_index_path(),
        {
            "version": CHAT_INDEX_VERSION,
            "chats": chats,
        },
    )


def _chat_metadata(chat_id: str, entry: dict[str, Any]) -> dict[str, Any]:
    """Build public metadata from an already-loaded index entry."""
    return {
        "id": chat_id,
        "name": entry.get("name", ""),
        "created_at": entry.get("created_at", ""),
        "updated_at": entry.get("updated_at", ""),
        "model": entry.get("model", ""),
        # Older indexes predate title ownership. Their names were generated by
        # Remie (there was no rename UI), so treating them as automatic keeps
        # adaptive titles working after an upgrade.
        "title_source": entry.get("title_source", "auto"),
    }


def find_chat_by_id(chat_id: str) -> dict[str, Any] | None:
    """Return a chat's index metadata for a uuid, or None."""
    entry = load_chat_index().get(chat_id)
    return _chat_metadata(chat_id, entry) if isinstance(entry, dict) else None


def list_chats() -> list[dict[str, Any]]:
    """Return [{id, name, created_at, updated_at, model}] newest first."""
    chats = []
    for chat_id, entry in load_chat_index().items():
        chats.append(
            {
                "id": chat_id,
                "name": entry.get("name", ""),
                "created_at": entry.get("created_at", ""),
                "updated_at": entry.get("updated_at", ""),
                "model": entry.get("model", ""),
                "title_source": entry.get("title_source", "auto"),
            }
        )
    return sorted(chats, key=lambda item: item["updated_at"], reverse=True)


def create_chat(name: str = DEFAULT_CHAT_NAME) -> dict[str, Any]:
    """Register a new chat and return its index entry (file written on save)."""
    name = " ".join(name.split())[:MEMORY_NAME_MAX_CHARS].rstrip() or DEFAULT_CHAT_NAME
    chat_id = str(uuid.uuid4())
    now = _dt.datetime.now().isoformat(timespec="seconds")
    chats = load_chat_index()
    chats[chat_id] = {
        "name": name,
        "created_at": now,
        "updated_at": now,
        "model": "",
        "title_source": "auto",
    }
    save_chat_index(chats)
    return _chat_metadata(chat_id, chats[chat_id])


def rename_chat(
    chat_id: str, name: str, *, title_source: str = "manual"
) -> dict[str, Any] | None:
    """Rename a chat and record whether a person or Remie chose the title."""
    chats = load_chat_index()
    if chat_id not in chats:
        return None
    name = " ".join(name.split())[:MEMORY_NAME_MAX_CHARS].rstrip()
    if not name:
        return _chat_metadata(chat_id, chats[chat_id])
    existing_names = {
        str(entry.get("name", "")).strip().lower()
        for other_id, entry in chats.items()
        if other_id != chat_id
    }
    if name.strip().lower() in existing_names:
        base = name
        suffix = 2
        candidate = f"{base} {suffix}"
        while candidate.strip().lower() in existing_names:
            suffix += 1
            suffix_text = f" {suffix}"
            candidate = (
                f"{base[: MEMORY_NAME_MAX_CHARS - len(suffix_text)].rstrip()}"
                f"{suffix_text}"
            )
        name = candidate
    chats[chat_id]["name"] = name
    chats[chat_id]["title_source"] = (
        title_source if title_source in {"auto", "manual"} else "manual"
    )
    save_chat_index(chats)
    return _chat_metadata(chat_id, chats[chat_id])


def delete_chat(chat_id: str) -> dict[str, Any] | None:
    """Remove a chat's file and index entry; returns the removed entry."""
    chats = load_chat_index()
    entry = chats.get(chat_id)
    if not isinstance(entry, dict):
        return None
    chat = _chat_metadata(chat_id, entry)
    path = chat_file_path(chat_id)
    if path.is_file():
        path.unlink()
    chats.pop(chat_id, None)
    save_chat_index(chats)
    return chat


def save_chat(
    chat_id: str,
    context_messages: list[dict[str, Any]],
    transcript: list[dict[str, Any]],
    token_usage: dict[str, int] | None = None,
) -> dict[str, Any] | None:
    """Persist a chat's resumable context and visible transcript.

    A brand-new default-named chat with nothing beyond the system prompt is
    dropped from the index instead of being saved, so unused Ctrl+L chats do
    not accumulate. ``token_usage`` ({"input_tokens", "output_tokens"}) is the
    per-chat cumulative LLM usage, restored when the chat is reopened.
    """
    chats = load_chat_index()
    if chat_id not in chats:
        return None
    has_content = bool(transcript) or len(context_messages) > 1
    path = chat_file_path(chat_id)
    if not has_content and not path.is_file():
        if chats[chat_id].get("name", "").strip().lower() == DEFAULT_CHAT_NAME.lower():
            chats.pop(chat_id, None)
            save_chat_index(chats)
            return None
    payload: dict[str, Any] = {
        "version": CHAT_FILE_VERSION,
        "id": chat_id,
        "context_messages": context_messages,
        "transcript": transcript,
    }
    if token_usage is not None:
        payload["token_usage"] = token_usage
    _write_json_atomic(path, payload)
    chats[chat_id]["updated_at"] = _dt.datetime.now().isoformat(timespec="seconds")
    save_chat_index(chats)
    return _chat_metadata(chat_id, chats[chat_id])


def load_chat(chat_id: str) -> dict[str, Any] | None:
    """Return {id, name, created_at, updated_at, model, context_messages,
    transcript} for a chat, or None when absent or corrupt."""
    chat = find_chat_by_id(chat_id)
    if chat is None:
        return None
    path = chat_file_path(chat_id)
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except OSError, UnicodeError, json.JSONDecodeError:
        return None
    if not isinstance(data, dict) or data.get("version") != CHAT_FILE_VERSION:
        return None
    context = data.get("context_messages")
    transcript = data.get("transcript")
    if not isinstance(context, list) or not isinstance(transcript, list):
        return None
    chat["context_messages"] = context
    chat["transcript"] = transcript
    usage = data.get("token_usage")
    chat["token_usage"] = (
        usage
        if isinstance(usage, dict)
        and isinstance(usage.get("input_tokens"), int)
        and isinstance(usage.get("output_tokens"), int)
        else {"input_tokens": 0, "output_tokens": 0}
    )
    return chat


def migrate_legacy_session() -> str | None:
    """Import a legacy .remie/session.json as the first chat, exactly once.

    The legacy file is only removed after the chat file and index entry have
    been written successfully, so an interrupted migration retries instead of
    losing data. Returns the created chat id, or None.
    """
    path = session_file_path()
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except OSError, UnicodeError, json.JSONDecodeError:
        return None
    if not isinstance(data, dict) or data.get("version") != LEGACY_SESSION_VERSION:
        return None
    messages = data.get("messages")
    if not isinstance(messages, list) or not messages:
        return None

    def _chat_title() -> str:
        for message in messages:
            if message.get("role") != "user":
                continue
            content = message.get("content")
            if isinstance(content, str) and content.strip():
                text = " ".join(content.split())
                if text.startswith("tool_result("):
                    continue
                return text[:MEMORY_NAME_MAX_CHARS].rstrip() or DEFAULT_CHAT_NAME
        return "Previous session"

    saved_at = str(
        data.get("saved_at") or _dt.datetime.now().isoformat(timespec="seconds")
    )
    chat_id = str(uuid.uuid4())
    chat_payload = {
        "version": CHAT_FILE_VERSION,
        "id": chat_id,
        "context_messages": messages,
        "transcript": [m for m in messages if m.get("role") != "system"],
    }
    _write_json_atomic(chat_file_path(chat_id), chat_payload)
    chats = load_chat_index()
    chats[chat_id] = {
        "name": _chat_title(),
        "created_at": saved_at,
        "updated_at": saved_at,
        "model": str(data.get("model", "")),
        "title_source": "auto",
    }
    save_chat_index(chats)
    path.unlink(missing_ok=True)
    return chat_id


def load_latest_chat() -> dict[str, Any] | None:
    """Return the most recently updated chat, migrating legacy sessions first."""
    migrate_legacy_session()
    for chat in list_chats():
        loaded = load_chat(chat["id"])
        if loaded is not None:
            return loaded
    return None
