"""Remie's tool implementations.

This package is a refactor of the former single-module ``remie/tools.py``.
Every public name is re-exported here so existing imports
(``from remie.tools import ...``) keep working unchanged.
"""

import subprocess  # noqa: F401 -- re-exported; tests patch remie.tools.subprocess.run

from remie.tools.common import _env_int

# Recomputed on importlib.reload so tests can override REMIE_COMMAND_TIMEOUT
# via the environment and reload the package (mirrors the old module behavior).
RUN_COMMAND_TIMEOUT = _env_int("REMIE_COMMAND_TIMEOUT", 30)

from remie.tools.ask_user import ask_user_tool
from remie.tools.chats import (
    CHAT_FILE_VERSION,
    CHAT_INDEX_VERSION,
    DEFAULT_CHAT_NAME,
    LEGACY_SESSION_VERSION,
    chat_dir,
    chat_file_path,
    chat_index_path,
    create_chat,
    delete_chat,
    find_chat_by_id,
    list_chats,
    load_chat,
    load_chat_index,
    load_latest_chat,
    migrate_legacy_session,
    rename_chat,
    save_chat,
    save_chat_index,
    session_file_path,
)
from remie.tools.commands import (
    DANGEROUS_COMMAND_PATTERNS,
    RUN_COMMAND_MAX_OUTPUT,
    RUN_COMMAND_TIMEOUT as _RUN_COMMAND_TIMEOUT_SUBMODULE,
    TIMED_OUT_EXIT_CODE,
    get_blocked_command_reason,
    get_custom_blocked_commands,
    run_command_tool,
)
from remie.tools.common import (
    _env_int,
    _remie_dir,
    _write_json_atomic,
    resolve_abs_path,
)
from remie.tools.files import (
    DIFF_MAX_CHARS,
    GLOB_MAX_RESULTS,
    IGNORED_DIRS,
    IGNORED_SUFFIXES,
    TREE_MAX_DEPTH,
    TREE_MAX_ENTRIES,
    edit_file_tool,
    glob_files_tool,
    list_files_tool,
    read_file_tool,
    tree_files_tool,
)
from remie.tools.memory import (
    DEFAULT_MEMORY_NAME,
    MEMORY_INDEX_VERSION,
    MEMORY_NAME_MAX_CHARS,
    active_memory_file_path,
    create_launch_memory,
    create_memory,
    delete_memory,
    ensure_active_memory,
    ensure_general_memory,
    find_memory_by_id,
    find_memory_by_name,
    get_active_memory_id,
    list_memories,
    memory_dir,
    memory_file_path,
    memory_index_path,
    memory_tool,
    rename_memory,
    set_active_memory_id,
)
from remie.tools.registry import (
    TOOL_PARAMETERS,
    TOOL_REGISTRY,
    TOOL_SUMMARIES,
    get_tool_schemas,
    get_tool_str_representation,
    get_tool_summary,
)
from remie.tools.web import (
    SEARCH_RESULT_LIMIT,
    USER_AGENT,
    WEB_BODY_MAX_CHARS,
    WEB_MAX_BYTES,
    WebToolError,
    html_to_text,
    web_fetch_tool,
    web_search_tool,
)

__all__ = [
    "CHAT_FILE_VERSION",
    "CHAT_INDEX_VERSION",
    "DEFAULT_CHAT_NAME",
    "DEFAULT_MEMORY_NAME",
    "DIFF_MAX_CHARS",
    "DANGEROUS_COMMAND_PATTERNS",
    "GLOB_MAX_RESULTS",
    "IGNORED_DIRS",
    "IGNORED_SUFFIXES",
    "LEGACY_SESSION_VERSION",
    "MEMORY_INDEX_VERSION",
    "MEMORY_NAME_MAX_CHARS",
    "RUN_COMMAND_MAX_OUTPUT",
    "RUN_COMMAND_TIMEOUT",
    "SEARCH_RESULT_LIMIT",
    "TIMED_OUT_EXIT_CODE",
    "TOOL_PARAMETERS",
    "TOOL_REGISTRY",
    "TOOL_SUMMARIES",
    "TREE_MAX_DEPTH",
    "TREE_MAX_ENTRIES",
    "USER_AGENT",
    "WEB_BODY_MAX_CHARS",
    "WEB_MAX_BYTES",
    "WebToolError",
    "_DD_SAFE_DEVICES",
    "__all__",
    "_env_int",
    "_migrate_to_uuid_index",
    "_remie_dir",
    "_tree_walk",
    "_write_json_atomic",
    "active_memory_file_path",
    "ask_user_tool",
    "chat_dir",
    "chat_file_path",
    "chat_index_path",
    "create_chat",
    "create_launch_memory",
    "create_memory",
    "delete_chat",
    "delete_memory",
    "edit_file_tool",
    "ensure_active_memory",
    "ensure_general_memory",
    "find_chat_by_id",
    "find_memory_by_id",
    "find_memory_by_name",
    "get_active_memory_id",
    "get_blocked_command_reason",
    "get_custom_blocked_commands",
    "get_tool_schemas",
    "get_tool_str_representation",
    "get_tool_summary",
    "glob_files_tool",
    "html_to_text",
    "list_chats",
    "list_files_tool",
    "list_memories",
    "load_chat",
    "load_chat_index",
    "load_latest_chat",
    "memory_dir",
    "memory_file_path",
    "memory_index_path",
    "memory_tool",
    "migrate_legacy_session",
    "read_file_tool",
    "rename_chat",
    "rename_memory",
    "resolve_abs_path",
    "run_command_tool",
    "save_chat",
    "save_chat_index",
    "session_file_path",
    "set_active_memory_id",
    "tree_files_tool",
    "web_fetch_tool",
    "web_search_tool",
]
